spring:
  activiti:
    check-process-definitions: false #自动检查、部署流程定义文件
    database-schema-update: true  #自动更新数据库结构
    history-level: full  #保存历史数据级别设置为full最高级别，便于历史数据的追溯 还有两个级别activity与none
    process-definition-location-prefix: classpath:/processes/
    #process-definition-location-suffixes:
    #  - **.bpmn20.xml
    #  - **.bpmn
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.72.128:3306/activiti?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 111111